menu/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.MenuList.as_view(), name='menu'),
    path('<slug:slug>/', views.menu_detail, name='menu_detail'),
]

saporedm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render


def custom_404(request, exception):
    return render(request, "404.html", status=404)


def custom_500(request):
    return render(request, "500.html", status=500)


handler404 = "saporedm.urls.custom_404"
handler500 = "saporedm.urls.custom_500"

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    path("booking/", include("booking.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("menu/", include("menu.urls"), name="menu-urls"),
    path("mission/", include("mission.urls"), name="mission-urls"),
    path("", include("restaurant.urls"), name="restaurant-urls"),
]

menu/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Menu(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    content = models.TextField()
    excerpt = models.TextField(blank=True)


    class Meta:
        """
        Orders menus."
        """
        ordering = ["title", "slug"]

menu/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Menu
# Create your views here.


class MenuList(generic.ListView):
    queryset = Menu.objects.all()
    template_name = "menu/menu.html"
    paginate_by = 3


def menu_detail(request, slug):
    """
    Display an individual :model:`menu.Menu`.
    """

    queryset = Menu.objects.all()
    menu = get_object_or_404(queryset, slug=slug)

    return render(
        request,
        "menu/menu_detail.html",
        {"menu": menu},
    )

menu/templates/menu/menu.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- Displays The Menu List -->
<div class="menu-list">
    {% for menu in menu_list %}
    <a href="{% url 'menu_detail' menu.slug %}" class="menu-link">
        <!-- Conditional statement to display background image related to respective menu -->
        {% if menu.slug == 'wine-list' %}
        <div id="wine-list"  >
            <div class="menu-description" id="wine-cover-text">
                <h2 class="menu-title">{{ menu.title }}</h2>
                    <p class="menu-ex">{{ menu.excerpt }}</p>
            </div>
        </div>
        {% elif menu.slug == 'a-la-carte-menu' %}
        <div id="carte-list" >
            <div class="menu-description" id="carte-cover-text">
                <h2 class="menu-title">{{ menu.title }}</h2>
                <p class="menu-ex">{{ menu.excerpt }}</p>
            </div>
        </div>
        {% else %}
        <div id="dessert-list" >
            <div class="menu-description" id="dessert-cover-text">
                <h2 class="menu-title">{{ menu.title }}</h2>
                <p class="menu-ex">{{ menu.excerpt }}</p>
            </div>
        </div>
        {% endif %}
    </a>
    {% endfor %}
</div>
{% endblock content %}
</html>

menu/templates/menu/menu_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!-- Displays correct background image -->
{% if menu.slug == 'wine-list' %}
<div class="wine-menu">
    {% elif menu.slug == 'a-la-carte-menu' %}
    <div class="carte-menu">
        {% else %}
        <div class="dessert-menu">
            {% endif %}
            <div class="cover-menu">
                {% if user.is_authenticated %}
                <p id="auth"><i class="fa-regular fa-user"></i> {{ user }}</p>
                {% else %}
                <p id="auth">You are not logged in</p>
                {% endif %}
                <div class="menu">
                    <a href="{% url 'menu' %}" class="back-arrow"><i class="fa-solid fa-arrow-left"></i></a>
                    <h1 class="menu-page-title">{{ menu.title }}</h1>
                    <hr>
                    <p class="menu-text">{{ menu.content | safe }}</p>
                </div>
                {% endblock %}
            </div>
        </div>
    </div>
</div>